//
// Created by shenk on 10.01.2022.
//

#ifndef LFNP_PROTOCOLS_STATS_DESCRIPTIONS_H
#define LFNP_PROTOCOLS_STATS_DESCRIPTIONS_H
{
        {"tcp", {
            "Connections initiated",
            "Connections accepted",
            "Connections established",
            "Connections dropped",
            "Embryonic connections dropped",
            "Average minmss too low drops",
            "Conn. closed (includes drops)",
            "Segs where we tried to get rtt",
            "Times we succeeded",
            "Delayed acks sent",
            "Conn. dropped in rxmt timeout",
            "Retransmit timeouts",
            "Persist timeouts",
            "Keepalive timeouts",
            "Keepalive probes sent",
            "Connections dropped in keepalive",
            "Total packets sent",
            "Data packets sent",
            "Data bytes sent",
            "Data packets retransmitted",
            "Data bytes retransmitted",
            "Unnecessary packet retransmissions",
            "Ack-only packets sent",
            "Window probes sent",
            "Packets sent with urg only",
            "Window update-only packets sent",
            "Control (syn|fin|rst) packets sent",
            "Total packets received",
            "Packets received in sequence",
            "Bytes received in sequence",
            "Packets received with ccksum errs",
            "Packets received with bad offset",
            "Packets dropped for no reass space",
            "Packets received too short",
            "Duplicate-only packets received",
            "Duplicate-only bytes received",
            "Packets with some duplicate data",
            "Dup. bytes in part-dup. packets",
            "Out-of-order packets received",
            "Out-of-order bytes received",
            "Packets with data after window",
            "Bytes rcvd after window",
            "Packets rcvd after \"close\"",
            "Rcvd window probe packets",
            "Rcvd duplicate acks",
            "Rcvd acks for unsent data",
            "Rcvd ack packets",
            "Bytes acked by rcvd acks",
            "Rcvd window update packets",
            "Segments dropped due to paws",
            "Times hdr predict ok for acks",
            "Times hdr predict ok for data pkts",
            "Pcbachemiss"
            "Times cached rtt in route updated",
            "Times cached rttvar updated",
            "Times cached ssthresh updated",
            "Times rtt initialized from route",
            "Times rttvar initialized from rt",
            "Timeout in persist state",
            "Bogus syn, e.g. premature ack",
            "Resends due to mtu discovery",
            "Listen queue overflows",
            "Ignored rsts in the window",
            "Entry added to syncache",
            "Syncache entry was retransmitted",
            "Duplicate syn packet",
            "Could not reply to packet",
            "Successful extraction of entry",
            "Syncache per-bucket limit hit",
            "Syncache cache limit hit",
            "Rst removed entry from syncache",
            "Timed out or listen socket gone",
            "Syncache entry aborted",
            "Removed due to bad ack",
            "Icmp unreachable received",
            "Zalloc() failed",
            "Syn cookie sent",
            "Syn cookie received",
            "Entry added to hostcache",
            "Hostcache per bucket limit hit",
            "Drop fin_wait_2 connection after time limit",
            "Sack recovery episodes",
            "Sack rexmit segments  ",
            "Sack rexmit bytes     ",
            "Sack blocks (options) received",
            "Sack blocks (options) sent    ",
            "Sack lost retransmission recovered",
            "Times scoreboard overflowed",
            "Ecn congestion experienced",
            "Ecn capable transport",
            "Ecn capable transport",
            "Ecn successful handshakes",
            "# times ecn reduced the cwnd",
            "Total matching signature received",
            "Total bad signature received",
            "Failed to make signature",
            "No signature expected by socket",
            "No signature provided by segment",
            "Black hole count",
            "Bh at min mss count",
            "Black hole failure count",
            "Packets encap's in udp received",
            "Packets that had errors that were udp encaped",
            "Number of acks arriving with dsacks",
            "Number of bytes dsack'ed no tlp",
            "Number of bytes dsack'ed due to tlps"
        }},
        {"udp", {
                "Total input packets",
                "Packet shorter than header",
                "Checksum error",
                "No checksum",
                "Data length larger than packet",
                "No socket on port",
                "Of above, arrived as broadcast",
                "Not delivered, input socket full",
                "Input packets missing pcb cache",
                "Input packets not for hashed pcb",
                "Total output packets",
                "Output packets on fast path",
                "Of no socket on port, arrived as multicast",
                "Blocked by multicast filter"
        }},
        {"ip", {
                "Total packets received",
                "Checksum bad",
                "Packet too short",
                "Not enough data",
                "Ip header length < data size",
                "Ip length < ip header length",
                "Fragments received",
                "Frags dropped (dups, out of space)",
                "Fragments timed out",
                "Packets forwarded",
                "Packets fast forwarded",
                "Packets rcvd for unreachable dest",
                "Packets forwarded on same net",
                "Unknown or unsupported protocol",
                "Total ip packets generated here",
                "Lost packets due to nobufs, etc.",
                "Total packets reassembled ok",
                "Datagrams successfully fragmented",
                "Output fragments created",
                "Don't fragment flag was set, etc.",
                "Error in option processing",
                "Packets discarded due to no route",
                "Ip version != 4",
                "Total raw ip packets generated",
                "Ip length > max ip packet size",
                "Multicasts for unregistered grps",
                "No match gif found",
                "Invalid address on header"
        }},
        {"igmp", {
                "Version & Length"
                "Total igmp messages received",
                "Received with too few bytes",
                "Received with ttl other than 1",
                "Received with bad checksum",
                "Received igmpv1/igmpv2 queries",
                "Received igmpv3 queries",
                "Received invalid queries",
                "Received general queries",
                "Received group queries",
                "Received group-source queries",
                "Dropped group-source queries",
                "Received membership reports",
                "Received invalid reports",
                "Received reports for our groups",
                "Received w/o router alert option",
                "Sent membership reports"
        }},
        {"icmp", {
                "Number of calls to icmp_error",
                "No error 'cuz old ip too short",
                "No error 'cuz old was icmp",
                "Icmp_code out of range",
                "Packet < icmp_minlen",
                "Bad checksum",
                "Calculated bound mismatch",
                "Number of responses",
                "B/mcast echo requests dropped",
                "B/mcast tstamp requests dropped",
                "Bad return address",
                "No route back"
        }}

};

#endif //LFNP_PROTOCOLS_STATS_DESCRIPTIONS_H
